# Generated by Django 3.2.6 on 2021-08-20 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, choices=[('W', 'Weekday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=50)),
                ('line', models.CharField(blank=True, max_length=50)),
                ('station_number', models.CharField(blank=True, max_length=50)),
                ('station', models.CharField(blank=True, max_length=50)),
                ('time01', models.FloatField()),
                ('time02', models.FloatField()),
                ('time03', models.FloatField()),
                ('time04', models.FloatField()),
                ('time05', models.FloatField()),
                ('time06', models.FloatField()),
                ('time07', models.FloatField()),
                ('time08', models.FloatField()),
                ('time09', models.FloatField()),
                ('time10', models.FloatField()),
                ('time11', models.FloatField()),
                ('time12', models.FloatField()),
                ('time13', models.FloatField()),
                ('time14', models.FloatField()),
                ('time15', models.FloatField()),
                ('time16', models.FloatField()),
                ('time17', models.FloatField()),
                ('time18', models.FloatField()),
                ('time19', models.FloatField()),
                ('time20', models.FloatField()),
                ('time21', models.FloatField()),
                ('time22', models.FloatField()),
                ('time23', models.FloatField()),
                ('time24', models.FloatField()),
                ('time25', models.FloatField()),
                ('time26', models.FloatField()),
                ('time27', models.FloatField()),
                ('time28', models.FloatField()),
                ('time29', models.FloatField()),
                ('time30', models.FloatField()),
                ('time31', models.FloatField()),
                ('time32', models.FloatField()),
                ('time33', models.FloatField()),
                ('time34', models.FloatField()),
                ('time35', models.FloatField()),
                ('time36', models.FloatField()),
                ('time37', models.FloatField()),
                ('time38', models.FloatField()),
                ('time39', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='traffic.trafficdb')),
            ],
        ),
    ]
